---
title: "rbi_analysis"
output:
  html_document: default
  pdf_document: default
date: "2024-02-29"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = TRUE,
	message = FALSE,
	warning = FALSE
)
```

```{r}
library(tidyverse)
```

```{r}
player_stats = read_csv("data/HR-RBI-AVG-SLG.csv")
ab_runners_on = read_csv("data/ab-w-runnerson.csv")

ab = ab_runners_on %>% 
  select(Season, Name, ABwROB = AB) 

stats = player_stats %>% 
  select(PlayerId, Season, Name, PA:SLG) %>% 
  inner_join(ab, by = c("Season", "Name"))

```

```{r}
#linear model of RBI
m1 = lm(RBI ~ HR + AVG + SLG + ABwROB, data = stats)
summary(m1)
```

```{r}
stats_w_expected = stats %>% 
  cbind(predicted_rbi = m1$fitted.values)

stats_w_expected %>% 
  ggplot(aes(x=predicted_rbi, y=RBI), ) +
  geom_point(color = "blue", size = 1) +
  geom_abline(color = "black", linetype = "dashed", size = 0.5) +
  labs(x = "RBI", y = "Predicted RBI",
       title = "Predicted RBI vs Actual 2015-2023",
       subtitle = "All Player Seasons with > 200 PA")
```


```{r}
#aggregate seasons
rbi_vs_expected = stats_w_expected %>% 
  group_by(Name) %>% 
  summarise(HR = sum(HR), AVG = sum(PA*AVG)/sum(PA), SLG = sum(PA*SLG)/sum(PA),
            ABwROB = first(ABwROB), RBI = sum(RBI), predicted_RBI = round(sum(predicted_rbi), 1)) %>%
  mutate(Difference = RBI - predicted_RBI) %>%
  select(Name:SLG, ABwROB, RBI:Difference) %>% 
  mutate(across(c("AVG", "SLG"), round, 3)) %>%
  arrange(Difference)

knitr::kable(rbi_vs_expected[1:30,])
```

  
  
